language: cpp
sudo: false

addons:
  apt:
    packages:
      - cmake
      - libsdl-dev
      - libsdl-gfx1.2-dev
compiler:
  - gcc
  - clang

script:
  - mkdir -p bld
  - cd bld
  - cmake ..
  - make
